version: '2'

services:
  db:
    image: mysql:8
    container_name: db_mysql_container
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: pizzas
      MYSQL_ROOT_PASSWORD: $root_password
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - '3307:3306'
    expose:
      - '3307'
  api:
    build: .
    container_name: django_container
    command: bash -c "pip install -q -r requirement.txt &&
                      python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db